# name: CI

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
#   # workflow_dispatch:
#   # schedule:
#     # - cron: '0 0 * * 0'  # Runs weekly on Sundays at midnight

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     # steps:

#   test:
#     runs-on: ubuntu-latest
#     needs: build
#     # steps: 

#   deploy:
#     name : Deploy to aws EC2
#     runs-on: ubuntu-latest
#     needs: test
    
#     steps: